version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.13.3
    - 2.13.4
    - 2.14.0
    - 2.14.1
    - 3.2.0
    - 3.2.1
    - 3.3.0
    - 3.3.1
  - dependency-name: gatsby
    versions:
    - 2.32.10
    - 2.32.4
    - 2.32.6
    - 2.32.8
    - 2.32.9
    - 3.2.0
    - 3.2.1
    - 3.3.0
    - 3.3.1
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-plugin-sitemap
    versions:
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-plugin-offline
    versions:
    - 3.10.0
    - 3.10.1
    - 3.9.0
    - 4.2.0
    - 4.3.0
  - dependency-name: gatsby-image
    versions:
    - 2.10.0
    - 2.11.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-remark-copy-linked-files
    versions:
    - 3.2.0
    - 4.0.0
  - dependency-name: gatsby-remark-prismjs
    versions:
    - 4.2.0
    - 5.0.0
  - dependency-name: gatsby-plugin-typescript
    versions:
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.10.0
    - 2.11.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-plugin-sass
    versions:
    - 3.1.0
    - 3.2.0
    - 4.2.0
    - 4.3.0
  - dependency-name: gatsby-plugin-google-analytics
    versions:
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-transformer-remark
    versions:
    - 2.15.0
    - 2.16.0
    - 3.2.0
    - 4.0.0
  - dependency-name: gatsby-transformer-json
    versions:
    - 2.10.0
    - 2.11.0
    - 3.2.0
    - 3.3.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.20.0
    - 4.21.0
  - dependency-name: typed-scss-modules
    versions:
    - 4.1.0
    - 4.1.1
  - dependency-name: husky
    versions:
    - 5.1.1
    - 5.1.2
    - 5.1.3
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
  - dependency-name: react-bootstrap
    versions:
    - 1.5.0
  - dependency-name: "@types/prismjs"
    versions:
    - 1.16.3
  - dependency-name: "@types/react"
    versions:
    - 17.0.2
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.10.0
    - 3.9.0
  - dependency-name: gatsby-remark-smartypants
    versions:
    - 2.10.0
    - 2.9.0
  - dependency-name: bootstrap
    versions:
    - 4.6.0
